Item.create(name: "G-Fax printer", price: 122, description: "A very good and cheap printer", group: "printer", details: "|%|rr|%|color:red|%|")
Item.create(name: "Xerox", price: 233, description: "High quality image analyses", group: "scanner", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Office's paper-A35", price: 227, description: "A very big package of multicolor paper", group: "paper", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Jenny's Ink.", price: 2342, description: "Very cheap cartridge!", group: "cartridge", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "G-Pen shredder", price: 345, description: "Ce qui peut être mieux qu'un fromage?", group: "shredder", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Loco's Pins", price: 2235, description: "Multicolored pin", group: "other", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Green Folder", price: 1120, description: "Folder to store documents", group: "other", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Laminator", price: 233, description: "Make your documents shiny", group: "laminator", details: "|%|phys|%|color:black|!|weight:12|%|")
Item.create(name: "Loco's bookbinder", price: 534, description: "How does this work?", group: "bookbinder", details: "|%|phys|%|color:black|!|weight:12|%|")
Feedback.create(item_id: 1, user_id: 1, rate: 5, review: "Wow! So tasty! So yummy! So doge!")
Feedback.create(item_id: 2, user_id: 1, rate: 3, review: "Kind of dissapointing")
Feedback.create(item_id: 3, user_id: 1, rate: 5, review: "Never felt so good before")
Feedback.create(item_id: 4, user_id: 1, rate: 4, review: "It's good")
Feedback.create(item_id: 5, user_id: 1, rate: 2, review: "PLEASE AT ANY CASE DON'T BUY THIS!")
